### ISSUE TITLE
GormMigrationRunner bean not created when DataSource injected into RabbitMQ ChannelInitializer

### ISSUE THREAD

**Issue by matthew-long** [micronaut-projects/micronaut-liquibase#21]
I came across this by accident.
I had injected a datasource into my bean that extends the RabbitMQ ChannelInitializer abstract class.

I found that Liquibase never ran and when I put a breakpoint in the GormMigrationRunner onCreated method it was never called.

If I remove the injected datasource then Liquibase will run again.

See MyClass.groovy in https://github.com/matthew-long/micronaut-gorm-liquibase

**Comment by ilopmar** [comment]
The same happens with a Java application so it's not related to GORM: https://github.com/micronaut-core-issues-test-app/micronaut-liquibase-rabbit-issue-21

**Comment by ilopmar** [comment]
After being digging a little bit more, it has nothing to do with RabbitMQ or GORM. With the following class:
```
@Singleton
class MyClass implements BeanCreatedEventListener<Book> {

    private final javax.sql.DataSource dataSource;

    MyClass(javax.sql.DataSource dataSource) {
        this.dataSource = dataSource;
    }

    @Override
    public Book onCreated(BeanCreatedEvent<Book> event) {
        return event.getBean();
    }
}
```

The liquibase migrations are not executed because somehow the BeanCreatedEvent for DataSource is not triggered. 

The following 2 versions work:
```
@Singleton
class MyClass implements BeanCreatedEventListener<Book> {

    @Override
    public Book onCreated(BeanCreatedEvent<Book> event) {
        return event.getBean();
    }
}
```

```
@Singleton
class MyClass {

    private final javax.sql.DataSource dataSource;

    MyClass(javax.sql.DataSource dataSource) {
        this.dataSource = dataSource;
    }
}
```

This is a chicken and egg problem and it happens because the `BeanCreatedEvent` listeners are created first, so they can't pick up beans created during the bean created event listener initialization.

As a workaround you can inject `Provider<DataSource>` and everything will work as expected.
