### ISSUE TITLE
NoSuchMethodException: liquibase.change.AddColumnConfig.<init>() when running native image

### ISSUE THREAD

**Issue by lukasstanek** [micronaut-projects/micronaut-liquibase#216]
### Expected Behavior

The program should execute all migrations correctly.

### Actual Behaviour

Following exception is thrown: `Caused by: java.lang.NoSuchMethodException: liquibase.change.AddColumnConfig.<init>()`

### Steps To Reproduce

Not sure, I have a set of ordinary changesets, which work when using the jvm version. 

probably this class `liquibase.change.AddColumnConfig.<init>()` needs to be added to the reflection-config? 

### Environment Information

Building a native image. 

### Version

3.2.0

**Comment by ilopmar** [comment]
Probably we are missing some classes in the GraalVM reflect-config. Do you have a sample app that reproduces the problem?

**Comment by lukasstanek** [comment]
hey, made a minimal repo for reproduction. 
just run ./gradlew dockerBuildNative and replace the hash in the docker-compose.yml with the one from the gradle build.

seems that the error arises in migration 02 and 01 goes through alright.

https://github.com/lukasstanek/mn-graal-liquibase-bug

**Comment by ilopmar** [comment]
The fix is included in `micronaut-liquibase` v5.0.1.

A couple of comments regarding your example:
- As you are using Lombok you need to make sure its annotation processor is executed **before** Micronaut's. I'm surprised your application works because you are missing it. See https://micronaut.io/launch?type=DEFAULT&name=demo&package=com.example&javaVersion=JDK_11&lang=JAVA&build=GRADLE&test=JUNIT&features=lombok&version=3.2.3&activity=diff
- `@MappedSuperclass` is not inherited so you need to annotate your child classes (`User` and `Address` in your example) with it. If you don't, you will see errors like `Message: No identifier specified for entity: mn.graal.liquibase.bug.model.Address`.

**Comment by lukasstanek** [comment]
hey, thanks so much for the super fast fix! Will test it out, later. 
Also thanks for the input, I'll have a look
