### ISSUE TITLE
Liquibase version update to 4.23.0 

### ISSUE THREAD

**Issue by DmitryKubahov** [micronaut-projects/micronaut-liquibase#429]
### Expected Behavior

Liquibase removed the release of **4.22.0** version - [link](https://github.com/liquibase/liquibase/releases/tag/v4.22.0) and micronuat-liquibase should use a newer version of it **4.23.0**
The issues connected to the checksum calculation and we got it. Long story short -> after upgrading to the latest micronaut 4.0.2 our changsets were declined, as checksums are changed (changesets were not changed at all).

### Actual Behaviour

With current version of liquibase 4.22.0 changesets will be declined as checksums calculation issue in the liquibase.

### Version

6.0.1

**Comment by richardwilko** [comment]
We're also experiencing issues following the liquibase upgrade, but I think it's slightly more complex fix than just upgrading to 4.23.

Liquibase have bumped the checksum algo from v8 to v9 in 4.22. From my understand, normally it should handle this upgrade automatically, but the micronaut integration tries to be more optimal with the `isUpdateNeeded` method.  This very method is throwing the exception because the checksum is different (due to version upgrade).

They claim 4.23 supports multiple algos, but my limited testing shows otherwise. Forcing the dependency to 4.23.1 locally, I still get an error.

What did work for me was subclassing `LiquibaseMigrator` so I could get a handle on a liquibase instance to conditionally call `clearCheckSums` and then `changeLogSync` to force a recalculate of the checksum with the new algo, if checksum we currently have stored is less than latest.
Another option that worked was simply calling `liquibase.changeLogSync`, without the optimisation added my micronaut.

An ideal enhancement would be to provide flags allowing us to bypass the micronaut optimised check.

**Comment by richardwilko** [comment]
@DmitryKubahov appreciate 4.19 to 4.23 is probably a liquibase issue rather than micronaut.
Liquibase did correctly identify the v8 checksum when using 4.23, but the checksum value it calculated was still different.
Forcing an update to the v9 checksum algo seems to work though (4.22 does this)

**Comment by sdelamo** [comment]
@timyates can you try to create a database with Micronaut Framework 3 and liquibase (create 1 table). Then, please update the app to the latest version of Micronaut Framework 4 and add a migration (e.g. add a column). see everything works fine.

**Comment by timyates** [comment]
Ok, so here are my findings...

❌ Creating an app with **Micronaut 3.8** with a liquibase migration, and then updating to **4.1.6** fails with the checksum error reported here

> [!TIP]  
> A 4.1.6 build can be made to work more simply by excluding `liquibase-core` from the `micronaut-liquibase` dependency, and then separately pulling in a fixed version such as `4.23.2`
> ie: (for Gradle with a Kotlin DSL)
> ```
>   implementation("io.micronaut.liquibase:micronaut-liquibase") {
>        exclude(group = "org.liquibase", module = "liquibase-core")
>   }
>   implementation("org.liquibase:liquibase-core:4.23.2")
> ```

✅ Creating an app with **Micronaut 3.8** with a liquibase migration, and then updating to **4.2.3** passes (as it uses the new, fixed version of liquibase)

As this works with the latest micronaut, and the workaround I show above, I'm going to close this

Thanks for reporting it!
